### ISSUE TITLE
[earth-tiles-db] create a db for natural earth & osm_land

### ISSUE THREAD

**Issue by syncush** [MapColonies/microcOSM#21]
We should 
* be able to update the DB on a regular basis regardless of the service using it (mvt or rasterized).
* define a set such that mvt and rasterized will share the same base earth.
* the container should accept a cronjob expression that will indicate the update check & interval of the db data.
* for now we would include both natural earth and external-data.yml.

I think we should use the [get-external-data.py](https://github.com/gravitystorm/openstreetmap-carto/blob/master/scripts/get-external-data.py).

**Comment by CptSchnitz** [comment]
as a stop gap measure, we have built a simple container in #29 to load the vector tiles external data.
It's not loaded into a separate database yet, but its not a part of imposm image anymore.
